### ISSUE TITLE
Collision in naming

### ISSUE THREAD

**Issue by DaveDavenport** [marvinkreis/rofi-file-browser-extended#14]
This plugin now collides in name  with its original ("file-browser"). 

Is it an idea to replace https://github.com/davatorium/rofi-file-browser by this one?
(we keep plugins close to rofi itself)

**Comment by marvinkreis** [comment]
The idea was that this plugin is kind of a superset of the original plugin, so I doubt that many users would have both installed. But I'm not opposed to replacing the original plugin with this one. Feel free to do whatever you want with this plugin :)

**Comment by DaveDavenport** [comment]
Not sure if we can move this repo to there or we just need to clone it there. I might need to make  you member of the davatorium org.

**Comment by marvinkreis** [comment]
Isn't there also a way to mirror a repo on github? I guess that would be the easiest way.

**Comment by marvinkreis** [comment]
Should be fixed in #32. It's renamed to `file-browser-extended` now.

**Comment by DaveDavenport** [comment]
great!
