### ISSUE TITLE
Feature request: custom commands on .. just run in the current directory

### ISSUE THREAD

**Issue by idanarye** [marvinkreis/rofi-file-browser-extended#19]
Currently highlighting `..` and hitting `Shift+Return` will prompt a custom command selection - for the parent directory. While this behavior is consistent and technically correct, it is not very useful as users entering a directory are not interested in running commands on the parent directory.

I think it'll be better if running custom commands on `..` will run them on the current directory - or at least run them **in** the current directory without arguments.

**Comment by marvinkreis** [comment]
I added the option `-file-browser-open-parent-as-self` to do this. I don't think it makes sense to make this the default behaviour, because, as you said, treating it as `..` is consistent.
