### ISSUE TITLE
Build fails with undeclared identifier 

### ISSUE THREAD

**Issue by anoduck** [marvinkreis/rofi-file-browser-extended#20]
I run OpenBSD and am recieving the following errors attempting to build the files:
```
/home/USER/rofi-file-browser-extended/src/files.c:124:65: error: use of undeclared identifier 'FTW_ACTIONRETVAL'
    int nftw_flags = fd->follow_symlinks ? FTW_ACTIONRETVAL : ( FTW_ACTIONRETVAL | FTW_PHYS );
                                                                ^
/home/USER/rofi-file-browser-extended/src/files.c:124:44: error: use of undeclared identifier 'FTW_ACTIONRETVAL'
    int nftw_flags = fd->follow_symlinks ? FTW_ACTIONRETVAL : ( FTW_ACTIONRETVAL | FTW_PHYS );
                                           ^
/home/USER/rofi-file-browser-extended/src/files.c:181:16: error: use of undeclared identifier 'FTW_CONTINUE'
        return FTW_CONTINUE;
               ^
/home/USER/rofi-file-browser-extended/src/files.c:184:16: error: use of undeclared identifier 'FTW_SKIP_SUBTREE'
        return FTW_SKIP_SUBTREE;
               ^
/home/USER/rofi-file-browser-extended/src/files.c:187:16: error: use of undeclared identifier 'FTW_SKIP_SUBTREE'
        return FTW_SKIP_SUBTREE;
               ^
/home/USER/rofi-file-browser-extended/src/files.c:259:16: error: use of undeclared identifier 'FTW_SKIP_SUBTREE'
        return FTW_SKIP_SUBTREE;
               ^
/home/USER/rofi-file-browser-extended/src/files.c:261:16: error: use of undeclared identifier 'FTW_CONTINUE'
        return FTW_CONTINUE;
               ^
7 errors generated.
*** Error 1 in . (CMakeFiles/filebrowser.dir/build.make:89 'CMakeFiles/filebrowser.dir/src/files.c.o': /usr/bin/cc -Dfilebrowser_EXPORTS -I/...)
*** Error 1 in . (CMakeFiles/Makefile2:105 'CMakeFiles/filebrowser.dir/all')
*** Error 1 in /home/USER/rofi-file-browser-extended (Makefile:130 'all')
```
Not sure where `ntfw_flags` is coming from? I was able to compile libnkutils independently, but had difficulty compiling it as a submodule for some reason.

**Comment by marvinkreis** [comment]
Hi. The problem is that I currently use the GNU extension of the `nftw` function to list files. I am planning to change this, since it is not compatible with OpenBSD. I've pushed some changes to the `develop` branch to remove `nftw`, so you can use that for now (but it doesn't handle recursive symlinks yet).

**Comment by marvinkreis** [comment]
Oh, and it would be nice if you could tell me if the version on the `develop` branch compiles on OpenBSD, because I don't have an installation to test it on :).

**Comment by anoduck** [comment]
@marvinkreis Sorry for the late response, life got busy...college...you know. 
I have been wanting to get this project running on my box now for some time. So, I will pull the development down and test it for you this weekend.

**Comment by jirutka** [comment]
I encountered the same problem on Alpine Linux (musl libc).

**Comment by anoduck** [comment]
@jirutka Thanks. Big fan of Alpine Linux, use it on my laptop.

**Comment by jirutka** [comment]
Glad to hear that! :) You can now install package [rofi-file-browser-extended](https://pkgs.alpinelinux.org/packages?name=rofi-file-browser-extended&branch=edge) from Alpine Edge.

**Comment by anoduck** [comment]
> Glad to hear that! :) You can now install package [rofi-file-browser-extended](https://pkgs.alpinelinux.org/packages?name=rofi-file-browser-extended&branch=edge) from Alpine Edge.

Sweetness!
