### ISSUE TITLE
Custom prompt string?

### ISSUE THREAD

**Issue by bbaserdem** [marvinkreis/rofi-file-browser-extended#22]
Is there a way to change the prompt string?

By display string, I mean the text mode descriptor that is the first string in the search bar.

Currently; mine says file-browser. I am able to change this behavior with original modes by;

```
configuration {
    display-drun:           "Bla ";
}
prompt {
    enabled:            true;
}
```

**Comment by marvinkreis** [comment]
Yes, you should be able to use `display-file-browser` to change the prompt.

**Comment by bbaserdem** [comment]
I was getting an error with the version in arch community repo (1.5.4) however changing to a VCS build (master branch) has fixed the error I was getting with setting the `display-file-browser` option in the rasi file.
