### ISSUE TITLE
Version 1.1.1 not tagged

### ISSUE THREAD

**Issue by jluttine** [marvinkreis/rofi-file-browser-extended#23]
Hi, and thanks for this amazing tool! Just wanted to point out that this commit https://github.com/marvinkreis/rofi-file-browser-extended/commit/b8ba0138ff12d7338a60e084020636f284ff56dc seems to be version 1.1.1 but it hasn't been tagged, so the latest release seems to be 1.1.0 here: https://github.com/marvinkreis/rofi-file-browser-extended/releases

Adding the tag would help packaging this for distros.

**Comment by marvinkreis** [comment]
Forgot to push the tags. Thank you for pointing it out.
