### ISSUE TITLE
Feature request: Resume from the directory of the previous choice

### ISSUE THREAD

**Issue by jluttine** [marvinkreis/rofi-file-browser-extended#28]
Just a thought: Quite often I want to open a file from the same directory I opened a file previously. Would it make sense to add support for such usecase? For instance, when given `-file-browser-resume`, the file browser would read the previously used directory from its internal cache file and after a file has been chosen, it'll update that directory value.

A possible extension: It would be possible to make it so that one can have multiple "profiles" so that they resume from the previous directory of that particular profile. For instance, if given `-file-browser-resume=some-music-player`, then it'll start from the directory it previously opened with that exact same option value given. And if given `-file-browser-resume=just-some-random-string`, it'll continue from the directory that was previously used with that exact option value.

Does this make sense?

**Comment by Kabouik** [comment]
I asked something similar in #26, so I second this request.

**Comment by humanplayer2** [comment]
I've made a hack: See https://github.com/marvinkreis/rofi-file-browser-extended/issues/26#issuecomment-1013735191

**Comment by marvinkreis** [comment]
I pushed some changes to implement this, see #26.
