### ISSUE TITLE
File-browser-extended is overriden by new internal file-browser

### ISSUE THREAD

**Issue by pianoslum** [marvinkreis/rofi-file-browser-extended#31]
Since version 1.6.1 rofi ships an integrated file browser, see https://github.com/davatorium/rofi/blob/1.6.1/releasenotes/1.6.1/release-1.6.1.markdown

Even though I installed the AUR-Pkg the old one seems to be chosen (at least the parameters for the extended file browser have no effect).

**Comment by marvinkreis** [comment]
Should be fixed in #32.
