### ISSUE TITLE
Cannot change icon theme?

### ISSUE THREAD

**Issue by humanplayer2** [marvinkreis/rofi-file-browser-extended#39]
I'm sorry if I'm asking a silly question, but I'm having issues changing the icon theme. It seems the icons shown are always the icons I have chosen at the OS level (I'm running Pop!_OS 21.10 with GNOME 40, have Rofi 1.6.1 and just build File Browser Extended).

E.g., I still see "humanity" icons if I set my system icons to "Humanity" and in terminal run 

`rofi -modi file-browser-extended -show file-browser-extended -file-browser-icon-theme "Adwaita"` . 

Similarly if my `~/.config/rofi/file-browser` contains just the line `icon-theme "Adwaita"`.

Can you suggest something I should do differently?

**Comment by marvinkreis** [comment]
The plugin switched to using rofi's own icon fetcher a while ago, so the icon theme is now set through rofi's configuration. Seems like I forgot to update the examples though. Sorry about that.
